version: '3'

services:
  db:
    image: postgres:15
    container_name: online_shop_postgres
    restart: always
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    expose:
      - 5432

  django:
    container_name: django
    build:
      context: .
    restart: always
    volumes:
      - .:/backend_apps
    depends_on:
      - db
      - redis
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - .nginx/default.conf:/etc/nginx/nginx.conf:ro

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - '6379:6379'
    restart: always

  worker:
    container_name: celery_worker
    restart: always
    build:
      context: .
    entrypoint: celery
    command: -A config.settings.celery worker -l info
    volumes:
      - .:/online_shop_backend/src/store_management/apps
    links:
      - redis
    depends_on:
      - db
      - django
      - redis

volumes:
  postgres_data:

