version: '3'


services:
  db:
    image: postgres:15
    container_name: online_shop_postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  drf_app:
    container_name: drf_app
    build:
      context: .
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/backend_apps
    depends_on:
      - db
      - redis
    links:
      - redis
      - db
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - '6379:6379'
    restart: always

  worker:
    container_name: celery_worker
    restart: always
    build:
      context: .
    entrypoint: celery
    command: -A config.settings.celery worker -l info
    volumes:
      - .:/online_shop_backend/src/store_management/apps
    links:
      - redis
    depends_on:
      - db
      - drf_app
      - redis

volumes:
  postgres_data:
