# Generated by Django 4.2.9 on 2024-01-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOfVariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'variation parent category',
                'verbose_name_plural': 'Parents of variations categories',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristicsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Characteristics category',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Description category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Products descriptions categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Photo')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount(Optional)')),
                ('bonuses', models.IntegerField(default=0, verbose_name='Bonuses(Optional)')),
                ('article', models.CharField(blank=True, max_length=8, null=True, verbose_name='Article')),
                ('availability_status', models.IntegerField(choices=[(1, 'in stock'), (2, 'awaiting arrival'), (3, 'low in stock'), (4, 'out of stock')], default=1)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='Category')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productdescription', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='VariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Variation category name')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_variation_categories', to='products.parentofvariationcategory', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Variations categories',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products/all/', verbose_name='Product photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AddField(
            model_name='productdescription',
            name='description_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productdescriptioncategory', verbose_name='Description category'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='characteristics name')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('characteristics_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.productcharacteristicscategory', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.products', verbose_name='Product')),
                ('variation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationcategory', verbose_name='Variation category')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'Product variations',
                'unique_together': {('product', 'variation_category')},
            },
        ),
    ]
