# Generated by Django 4.2.9 on 2024-01-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('coupons', '0001_initial'),
        ('users', '0011_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
                ('order_id', models.CharField(blank=True, max_length=7, null=True)),
                ('order_status', models.IntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Ready to ship'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Canceled')], default=1, verbose_name='Order status')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Total amount of order')),
                ('total_bonuses_amount', models.IntegerField(default=0, verbose_name='Total amount of bonuses for order')),
                ('payment_method', models.IntegerField(choices=[(1, 'By cash'), (2, 'By card')], default=1, verbose_name='Payment method')),
                ('delivery_method', models.IntegerField(choices=[(1, 'Courier'), (2, 'To the post office')], default=2, verbose_name='Delivery method')),
                ('activate_bonuses', models.BooleanField(default=False, verbose_name='Activate bonuses')),
                ('create_account', models.BooleanField(default=False, verbose_name='Create an account')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.usercoupons', verbose_name='Coupon')),
                ('shipping_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usershippinginfo', verbose_name='User shipping info')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['total_amount'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('total_price', models.IntegerField(default=0, verbose_name='Total price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'Items in order',
                'ordering': ['total_price'],
            },
        ),
    ]
